### ISSUE TITLE
uam not found

### ISSUE THREAD

**Issue by utdrmac** [kjake/docker-netatalk#1]
```
Apr 29 01:13:32.358455 afpd[37] {auth.c:1037} (info:AFPDaemon): uam: uam not found (status=-1)
Apr 29 01:13:32.358611 afpd[37] {status.c:644} (info:AFPDaemon): signature is FA69302C8EF31E72BC5CBD18F309C4C1
Apr 29 01:13:32.358872 afpd[37] {auth.c:111} (info:AFPDaemon): uam: "DHX2" available
Apr 29 01:13:32.358886 afpd[37] {auth.c:111} (info:AFPDaemon): uam: "No User Authent" available
```

**Comment by kjake** [comment]
very much apologize that GitHub didn't notify me about this, or at remind me ever?

Debian Stretch is still supplying Netatalk 2.x for install, so this container that I'm building uses un-official .deb's for 3.1.x, but I am not building those. I'm guessing that they are not configuring the build with --enable-krbV-uam.  I can look at trying to undertake this all in one container to see if the right libraries get built.

**Comment by kjake** [comment]
Looks like the libraries were built in `/usr/lib/netatalk`, but netatalk expects them in `/etc/netatalk/uams`.  I've added a symlink to the `Dockerfile`, which should correct the issue, but I don't have a reason to test.  macOS is or has removed support for AFP, so I don't run this service on my NAS anymore.

New image is live on Docker Hub: https://hub.docker.com/r/kjake/netatalk

**Comment by utdrmac** [comment]
What replaced AFP? It's so much faster than SMB. How does Timemachine work then if there's no AFP?

**Comment by kjake** [comment]
Nothing really replaced it, but TimeMachine works over Samba.  I switched to unRAID for my NAS and it has general support built-in, though I had to tweak it slightly.

Here's what I stuck in my Samba config to tweak TimeMachine - you'll need more to define the general shares. I'm sure someone's created a docker container though - I just haven't needed one.

```
# Time Machine settings
   vfs objects = catia fruit streams_xattr
   fruit:model = MacSamba
   fruit:advertise_fullsync = true
   fruit:metadata = stream
   fruit:veto_appledouble = no
   #default is yes, not necessary to specify fruit:posix_rename = no
   #default is yes, not necessary to specify fruit:zero_file_id = yes
   fruit:wipe_intentionally_left_blank_rfork = yes
   fruit:delete_empty_adfiles = yes
   ea support = yes
# Time Machine settings end
   veto files = /._*/.apdisk/.AppleDouble/.DS_Store/.TemporaryItems/.Trashes/desktop.ini/ehthumbs.db/Network Trash Folder/Temporary Items/Thumbs.db/
   delete veto files = yes
   socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=524288 SO_SNDBUF=524288
   durable handles = yes
   posix locking = no
   kernel oplocks = no
   kernel share modes = no
   create mask = 0666
   directory mask = 0777
```

**Comment by utdrmac** [comment]
Thanks for the info and thanks for the update. I'll keep it in mind if I ever switch to SMB.
